import streamlit as st
import json
import pandas as pd
from groq import Groq
from PyPDF2 import PdfReader
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table
from reportlab.lib.styles import getSampleStyleSheet

# ---------------- PAGE SETUP ----------------
st.set_page_config(page_title="ComplianceBot AI", page_icon="🛡️", layout="wide")
st.title("🛡️ ComplianceBot AI")
st.subheader("GST Invoice Compliance Scanner (India)")

# ---------------- SIDEBAR ----------------
api_key = st.sidebar.text_input("🔑 Groq API Key", type="password")
st.sidebar.markdown("### Pricing")
st.sidebar.markdown("""
🆓 Free: 3 invoices/month  
💼 SME: ₹1,499/month  
🧠 CA Plan: ₹24,999/year  
🏢 Enterprise: Custom  
""")

# ---------------- FUNCTIONS ----------------
def extract_text_from_pdf(pdf_file):
    reader = PdfReader(pdf_file)
    text = ""
    for page in reader.pages:
        if page.extract_text():
            text += page.extract_text()
    return text


def generate_pdf_report(df):
    file_path = "GST_Compliance_Report.pdf"
    doc = SimpleDocTemplate(file_path)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("<b>GST COMPLIANCE AUDIT REPORT</b>", styles["Title"]))
    elements.append(Paragraph("Generated by ComplianceBot AI", styles["Normal"]))
    elements.append(Paragraph("<br/>", styles["Normal"]))

    table_data = [df.columns.tolist()] + df.values.tolist()
    table = Table(table_data, repeatRows=1)
    elements.append(table)

    doc.build(elements)
    return file_path


# ---------------- MAIN LOGIC ----------------
if not api_key:
    st.info("👈 Shuru karne ke liye sidebar me Groq API Key daalein")
    st.stop()

client = Groq(api_key=api_key)

uploaded_file = st.file_uploader("📄 GST Invoice PDF Upload Karein", type="pdf")

if uploaded_file:
    with st.spinner("📖 PDF se text extract ho raha hai..."):
        invoice_text = extract_text_from_pdf(uploaded_file)

    st.success("PDF successfully read ✔")

    if st.button("🔍 Analyze GST Compliance"):
        with st.spinner("🧠 GST laws ke against analysis ho raha hai..."):

            prompt = f"""
You are a senior Indian GST Auditor who issues GST scrutiny notices.

Analyze the invoice strictly under Indian GST law.
Identify ALL compliance violations, if any.

For EACH violation, return output strictly in the following JSON ARRAY format:

[
  {{
    "violation": "",
    "law_reference": "",
    "monetary_risk_inr": "",
    "liable_party": "Seller / Buyer",
    "itc_impact": "Allowed / Blocked / Reversal Required",
    "risk_level": "LOW | MEDIUM | HIGH",
    "notice_probability_percent": ""
  }}
]

Invoice Text:
{invoice_text}

Rules:
- Mention exact GST Act section numbers
- Monetary risk must be in INR
- Notice probability must be numeric %
- Return ONLY valid JSON
"""

            try:
                completion = client.chat.completions.create(
                    model="llama-3.3-70b-versatile",
                    messages=[{"role": "user", "content": prompt}],
                )

                response_text = completion.choices[0].message.content
                violations = json.loads(response_text)

                df = pd.DataFrame(violations)

                st.success("✅ GST Compliance Analysis Complete")

                st.subheader("📋 Identified GST Violations")
                st.dataframe(df, use_container_width=True)

                avg_notice_risk = (
                    df["notice_probability_percent"]
                    .astype(str)
                    .str.replace("%", "")
                    .astype(float)
                    .mean()
                )

                st.metric(
                    label="⚠️ Overall GST Notice Probability",
                    value=f"{round(avg_notice_risk, 1)}%"
                )

                if st.button("📄 Download CA-Style GST Report (PDF)"):
                    pdf_file = generate_pdf_report(df)
                    with open(pdf_file, "rb") as f:
                        st.download_button(
                            "⬇️ Download GST Compliance Report",
                            f,
                            file_name="GST_Compliance_Report.pdf",
                            mime="application/pdf"
                        )

            except Exception as e:
                st.error("❌ Analysis failed")
                st.code(str(e))

# ---------------- FOOTER ----------------
st.markdown("---")
st.markdown(
    "⚖️ **Disclaimer:** This tool provides AI-based compliance insights and does not replace professional CA advice."
)
